version = 1

[merge]
automerge_label = "ğŸ¤– Auto merge"
blocking_labels = ["âŒ Invalid"]
method = "squash"

[merge.message]
title = "pull_request_title"
body_type = "markdown"
include_pr_number = true
strip_html_comments = true

[merge.automerge_dependecies]
versions = ["minor", "patch"]
usernames = ["dependabot"]