name: '[Heroku] Deploy'

on:
  push:
    branches:
      - master

jobs:
  builds:
    runs-on: ubuntu-latest
    name: 'Build'
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'zeta-discordbot'
          heroku_email: 'falcxxdev@gmail.com'
          buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git
        env:
          HD_TOKEN: ${{secrets.TOKEN}}
          HD_PREFIX: ${{secrets.PREFIX}}
          HD_MONGOURI: ${{secrets.MONGO_URI}}
          HD_TESTSERVER: ${{secrets.TESTSERVER}}
          HD_OWNERID: ${{secrets.OWNERID}}
          HD_ORIGIN_CHANNEL: ${{secrets.ORIGIN_CHANNEL}}
          HD_UPLOAD_CHANNEL: ${{secrets.UPLOAD_CHANNEL}}
          HD_HOLODEX_APIKEY: ${{secrets.HOLODEX_APIKEY}}
